services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab-server
    ports:
      - '${GITLAB_HTTP_PORT:-80}:80'
      - '${GITLAB_HTTPS_PORT:-443}:443'
      - '${GITLAB_SSH_PORT:-22}:22'
      - '${GITLAB_REGISTRY_PORT:-5050}:5050'
    environment:
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_OMNIBUS_CONFIG: external_url '${GITLAB_EXTERNAL_URL}'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    networks:
      - net

  runner:
    image: 'gitlab/gitlab-runner'
    container_name: gitlab-runner
    restart: unless-stopped
    links:
      - gitlab
    depends_on:
      - gitlab
    volumes:
      - ./runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

networks:
  net:
    external: false
